import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";
// import styles from './page.module.css';

const inter = Open_Sans({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: "Наш проект",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
      </body>
    </html>
  );
}
